[package]
name = "opentelemetry-tail-yew"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
futures = "0.3.28"
log = "0.4"
reqwasm = "0.5.0"
wasm-logger = "0.2"
yew = { version = "0.21", features = ["csr"] }
yew-agent = "0.3.0"
yew-router = "0.18"
